### ISSUE TITLE
[Improvement] Add Prometheus and Grafana in Helm Chart

### ISSUE THREAD

**Issue by unknowntpo** [apache/gravitino-playground#105]
At #56 , we haven't added Prometheus and Grafana to helm chart yet, so we plan to do it at this Issue.

Tasks:
 - [ ] Add `init/grafana/init.sh`, `init/prometheus/init.sh`, it will use `sed` to inject host name of other service into config files (similar to `init/hive/init.sh`)
- [ ] Add helm templates `prometheus.yml`, `grafana.yml` in `./helm-chart/templates`
  - We can simply use `hostPath` Persistence Volume to mount config file of Prometheus and Grafana into pods.
- [ ] Add corresponding values at `values.yml`
- [ ] Modify `./helm-chart/templates/NOTES.txt`, add description about these two services.

**Comment by orenccl** [comment]
This should be closed?

**Comment by unknowntpo** [comment]
Yeah, should be closed because we don't support helm chart anymore.
