### ISSUE TITLE
Some issues when using playground

### ISSUE THREAD

**Issue by FANNG1** [apache/gravitino-playground#6]
1.  Failed to launch playground. because I have a stoped docker container with the name "mysql" which conflict with playground container name, rename to "playground-mysql" "playground-postgresql"?   And I noticed playground export some famous ports like `3306` , maybe conflict with the port in local host.
2. I don't know when the playground is ready to use,  maybe we could provide a more meaningful message when it's ready or add some documents.
3. Add document about when playground is ready, which metalake, schema, tables are pre-created. 
4. Add document about how to explore existing metalake, schema, tables.

**Comment by justinmclean** [comment]
I also had an issue with ports as I had Postgres running locally, and the playground Postgres docker uses the same port. It's not entirely unexpected, but it could cause some people issues.

**Comment by qqqttt123** [comment]
> I also had an issue with ports as I had Postgres running locally, and the playground Postgres docker uses the same port. It's not entirely unexpected, but it could cause some people issues.

Maybe we can add the ports to the readme document and tell users how modify the ports.
