### ISSUE TITLE
[Improvement]: Copyright should be updated to 2024

### ISSUE THREAD

**Issue by unknowntpo** [apache/gravitino-playground#72]
In `0.6.0-incubating`, copyright is still 2023, which is obsolete.

<img width="1141" alt="Screenshot 2024-09-04 at 7 00 00 AM" src="https://github.com/user-attachments/assets/6d7d0568-1f1f-4fde-9317-a9c6360889ae">

**Comment by justinmclean** [comment]
This was updated the other week https://github.com/apache/gravitino/pull/4804

**Comment by justinmclean** [comment]
Note also that it should be copyrighted the ASF. While the ASF doesn't ask for the assignment of copyright, and the original owners (or more likely their employers) own the copyright in the bits they created, the ASF is the copyright holder of a release from an ASF project.

**Comment by unknowntpo** [comment]
Got it, thanks for your reply, @justinmclean
